swagger: "2.0"
info:
  title: Donation Prediction API
  description: API for predicting donation requests
  version: 1.0.0
host: localhost:9090
basePath: /
schemes:
  - http
paths:
  /predict:
    post:
      summary: Predicts donation request
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: input_data
          description: Input data for prediction
          required: true
          schema:
            type: object
            properties:
              Age:
                type: integer
              Medicines:
                type: integer
              Food:
                type: integer
              Monitory:
                type: integer
              Breed:
                type: string
              Sex:
                type: string
              Vaccinations Status:
                type: string
      responses:
        200:
          description: Successful prediction
          schema:
            type: object
            properties:
              Predictions:
                type: string